In [5]:
!pip install torchsummary

In [13]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc_0 = nn.Linear(100, 10, bias=False)
        self.fc_1 = nn.Linear(10, 5, bias=False)
        self.fc_2 = nn.Linear(5, 1, bias=False)
        
    def forward(self, x):
        x = self.fc_0(x)
        x = self.fc_1(x)
        x = self.fc_2(x)
        return x

model = Model()
print(model)
input = torch.rand(100)
output = model(input)
print(output)

summary(model, (100,), device="cpu")

Model(
  (fc_0): Linear(in_features=100, out_features=10, bias=False)
  (fc_1): Linear(in_features=10, out_features=5, bias=False)
  (fc_2): Linear(in_features=5, out_features=1, bias=False)
)
tensor([-0.0182], grad_fn=<SqueezeBackward4>)
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                   [-1, 10]           1,000
            Linear-2                    [-1, 5]              50
            Linear-3                    [-1, 1]               5
Total params: 1,055
Trainable params: 1,055
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [17]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc_1 = nn.Linear(1000, 100, bias=False)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        self.fc_2 = nn.Linear(100, 10, bias=False)
        self.fc_3 = nn.Linear(10, 5, bias=False)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.fc_1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc_2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc_3(x)
        x = self.softmax(x)
        return x

model = NeuralNetwork()
input = torch.rand((4,1000))
output = model(input)
print(output)
print(output.shape)
summary(model, (1000,), device="cpu")

tensor([[0.2120, 0.1772, 0.1916, 0.2044, 0.2148],
        [0.1932, 0.2119, 0.2076, 0.1717, 0.2156],
        [0.2025, 0.1852, 0.1964, 0.2022, 0.2136],
        [0.2040, 0.2019, 0.2014, 0.1991, 0.1935]], grad_fn=<SoftmaxBackward0>)
torch.Size([4, 5])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                  [-1, 100]         100,000
              ReLU-2                  [-1, 100]               0
           Dropout-3                  [-1, 100]               0
            Linear-4                   [-1, 10]           1,000
              ReLU-5                   [-1, 10]               0
           Dropout-6                   [-1, 10]               0
            Linear-7                    [-1, 5]              50
           Softmax-8                    [-1, 5]               0
Total params: 101,050
Trainable params: 101,050
Non-trainable params: 0
---------------------------------------

In [18]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc_1 = nn.Linear(256 * 256 * 3, 100, bias=False)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        self.fc_2 = nn.Linear(100, 10, bias=False)
        self.fc_3 = nn.Linear(10, 5, bias=False)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = x.view(-1, 256 * 256 * 3)
        x = self.fc_1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc_2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc_3(x)
        x = self.softmax(x)
        return x

model = NeuralNetwork()
input = torch.rand((10,256,256,3))
output = model(input)
print(output)
print(output.shape)
summary(model, (256,256,3,), device="cpu")

tensor([[0.1181, 0.2350, 0.1854, 0.2306, 0.2310],
        [0.1779, 0.2197, 0.1979, 0.2095, 0.1950],
        [0.1830, 0.2236, 0.2004, 0.2013, 0.1917],
        [0.1817, 0.2231, 0.2012, 0.2048, 0.1892],
        [0.1926, 0.2123, 0.2092, 0.1962, 0.1897],
        [0.1459, 0.2286, 0.2116, 0.2164, 0.1974],
        [0.1905, 0.2306, 0.2003, 0.1907, 0.1879],
        [0.1972, 0.2047, 0.2035, 0.1986, 0.1960],
        [0.1742, 0.2145, 0.1996, 0.2158, 0.1959],
        [0.1907, 0.2201, 0.1969, 0.2007, 0.1915]], grad_fn=<SoftmaxBackward0>)
torch.Size([10, 5])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                  [-1, 100]      19,660,800
              ReLU-2                  [-1, 100]               0
           Dropout-3                  [-1, 100]               0
            Linear-4                   [-1, 10]           1,000
              ReLU-5                   [-1, 10]               0
  

In [19]:
# 卷积层

In [20]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_1 = nn.Conv2d(3, 32, 3)
        self.relu = nn.ReLU()
        self.conv_2 = nn.Conv2d(32, 64, 3)
        self.conv_3 = nn.Conv2d(64, 128, 3)
        self.deconv_1 = nn.ConvTranspose2d(128, 64, 3)
        self.deconv_2 = nn.ConvTranspose2d(64, 32, 3)
        self.deconv_3 = nn.ConvTranspose2d(32, 10, 3)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.conv_1(x)
        x = self.relu(x)
        x = self.conv_2(x)
        x = self.relu(x)
        x = self.conv_3(x)
        x = self.relu(x)
        x = self.deconv_1(x)
        x = self.relu(x)
        x = self.deconv_2(x)
        x = self.relu(x)
        x = self.deconv_3(x)
        x = self.softmax(x)
        return x

model = NeuralNetwork()
input = torch.rand((10,3,224,224))
output = model(input)
print(output)
print(output.shape)
summary(model, (3,224,224), device="cpu")

tensor([[[[0.0955, 0.0946, 0.0940,  ..., 0.0934, 0.0940, 0.0949],
          [0.0948, 0.0935, 0.0932,  ..., 0.0928, 0.0934, 0.0948],
          [0.0944, 0.0930, 0.0921,  ..., 0.0909, 0.0929, 0.0949],
          ...,
          [0.0939, 0.0927, 0.0914,  ..., 0.0901, 0.0924, 0.0952],
          [0.0940, 0.0936, 0.0934,  ..., 0.0928, 0.0945, 0.0956],
          [0.0945, 0.0948, 0.0947,  ..., 0.0940, 0.0950, 0.0954]],

         [[0.1009, 0.1013, 0.1019,  ..., 0.1021, 0.1013, 0.1008],
          [0.1020, 0.1030, 0.1031,  ..., 0.1038, 0.1014, 0.1002],
          [0.1016, 0.1014, 0.1019,  ..., 0.1021, 0.1012, 0.1007],
          ...,
          [0.1014, 0.1006, 0.1017,  ..., 0.1027, 0.1013, 0.1008],
          [0.1001, 0.0995, 0.0995,  ..., 0.1001, 0.1002, 0.0998],
          [0.0990, 0.0977, 0.0981,  ..., 0.0988, 0.1000, 0.1006]],

         [[0.1021, 0.1032, 0.1035,  ..., 0.1046, 0.1048, 0.1034],
          [0.1030, 0.1040, 0.1048,  ..., 0.1061, 0.1055, 0.1040],
          [0.1040, 0.1040, 0.1061,  ..., 0

In [21]:
# 卷积+全连接网络实现图像分类

In [28]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_1 = nn.Conv2d(3, 32, 3)
        self.relu = nn.ReLU()
        self.conv_2 = nn.Conv2d(32, 64, 3)
        self.fc_1 = nn.Linear(64 * 220 * 220, 512)
        self.fc_2 = nn.Linear(512, 10)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.conv_1(x)
        x = self.relu(x)
        x = self.conv_2(x)
        x = self.relu(x)
        x = x.view(-1, 64 * 220 * 220)
        x = self.fc_1(x)
        x = self.relu(x)
        x = self.fc_2(x)
        x = self.softmax(x)
        return x

model = NeuralNetwork()
input = torch.rand((10,3,224,224))
output = model(input)
# print(output)
print(output.shape)
summary(model, (3,224,224), device="cpu")

torch.Size([10, 10])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 32, 222, 222]             896
              ReLU-2         [-1, 32, 222, 222]               0
            Conv2d-3         [-1, 64, 220, 220]          18,496
              ReLU-4         [-1, 64, 220, 220]               0
            Linear-5                  [-1, 512]   1,585,971,712
              ReLU-6                  [-1, 512]               0
            Linear-7                   [-1, 10]           5,130
           Softmax-8                   [-1, 10]               0
Total params: 1,585,996,234
Trainable params: 1,585,996,234
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.57
Forward/backward pass size (MB): 71.34
Params size (MB): 6050.10
Estimated Total Size (MB): 6122.01
----------------------------------------------------------------


In [30]:
# 复现LeNet-5

In [37]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class LeNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_1 = nn.Conv2d(3, 6, 5)
        self.pool_1 = nn.MaxPool2d(2)
        self.conv_2 = nn.Conv2d(6, 16, 5)
        self.pool_2 = nn.MaxPool2d(2)
        self.conv_3 = nn.Conv2d(16, 120, 5)
        self.fc_1 = nn.Linear(120, 84)
        self.fc_2 = nn.Linear(84, 10)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.conv_1(x)
        x = self.pool_1(x)
        x = self.conv_2(x)
        x = self.pool_2(x)
        x = self.conv_3(x)
        x = x.view(-1, 120 * 1 * 1)
        x = self.fc_1(x)
        x = self.fc_2(x)
        x= self.softmax(x)
        return x

model = LeNet()
input = torch.rand((5,3,32,32))
output = model(input)
# print(output)
print(output.shape)
summary(model, (3,32,32), device="cpu")

torch.Size([5, 10])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1            [-1, 6, 28, 28]             456
         MaxPool2d-2            [-1, 6, 14, 14]               0
            Conv2d-3           [-1, 16, 10, 10]           2,416
         MaxPool2d-4             [-1, 16, 5, 5]               0
            Conv2d-5            [-1, 120, 1, 1]          48,120
            Linear-6                   [-1, 84]          10,164
            Linear-7                   [-1, 10]             850
           Softmax-8                   [-1, 10]               0
Total params: 62,006
Trainable params: 62,006
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.01
Forward/backward pass size (MB): 0.06
Params size (MB): 0.24
Estimated Total Size (MB): 0.31
----------------------------------------------------------------


In [41]:
import torch.nn as nn
import torch.nn.functional as F
import torch
from torchsummary import summary


class MyBlock(nn.Module):
    def __init__(self, in_channel, out_channel):
        super().__init__()
        self.conv_1 = nn.Conv2d(in_channel, out_channel, 3, padding=1)
        self.bn_1 = nn.BatchNorm2d(out_channel)
        self.relu = nn.ReLU()
        self.conv_2 = nn.Conv2d(out_channel, out_channel, 3, padding=1)
        self.bn_2 = nn.BatchNorm2d(out_channel)
    def forward(self, x):
        x_1 = x
        x = self.conv_1(x)
        x = self.bn_1(x)
        x = self.relu(x)
        x = self.conv_2(x)
        x = self.bn_2(x)
        result = x + x_1
        return result

class MainNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv_1 = nn.Conv2d(3, 32, 3)
        self.conv_2 = nn.Conv2d(32, 64, 3)
        self.block_1 = MyBlock(64,64)
        self.block_2 = MyBlock(64,64)
        self.block_3 = MyBlock(64,64)

        self.fc = nn.Sequential(
            nn.Linear(64 * 220 * 220, 512),
            nn.Linear(512, 10)
        )
    def forward(self, x):
        x = self.conv_1(x)
        x = self.conv_2(x)
        x = self.block_1(x)
        x = self.block_2(x)
        x = self.block_3(x)
        x = x.view(-1, 64 * 220 * 220)
        x = self.fc(x)
        return x


model = MainNet()
input = torch.rand((5,3,224,224))
output = model(input)
# print(output)
print(output.shape)
summary(model, (3,224,224), device="cpu")

torch.Size([5, 10])
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 32, 222, 222]             896
            Conv2d-2         [-1, 64, 220, 220]          18,496
            Conv2d-3         [-1, 64, 220, 220]          36,928
       BatchNorm2d-4         [-1, 64, 220, 220]             128
              ReLU-5         [-1, 64, 220, 220]               0
            Conv2d-6         [-1, 64, 220, 220]          36,928
       BatchNorm2d-7         [-1, 64, 220, 220]             128
           MyBlock-8         [-1, 64, 220, 220]               0
            Conv2d-9         [-1, 64, 220, 220]          36,928
      BatchNorm2d-10         [-1, 64, 220, 220]             128
             ReLU-11         [-1, 64, 220, 220]               0
           Conv2d-12         [-1, 64, 220, 220]          36,928
      BatchNorm2d-13         [-1, 64, 220, 220]             128
          MyBlock-1