In [1]:
import torch

In [2]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [3]:
# 传入一个python的列表
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
# 传入numpy的array
import numpy as np

np_array = np.array([[1,2],[3,4]])

x_np = torch.tensor(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
# 保持x_data数据属性和形状

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

# 保持x_data的形状，重新定义x_data的数据属性

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6439, 0.7284],
        [0.2964, 0.5215]]) 



In [6]:
# 生成指定行列的数据tensor

shape=(2,3)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")

one_tensor = torch.ones(shape)
print(f"Random Tensor: \n {one_tensor} \n")

Random Tensor: 
 tensor([[0.7314, 0.9252, 0.3127],
        [0.4006, 0.4120, 0.0107]]) 

Random Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [7]:
if torch.cuda.is_available():
    gpu_tensor = rand_tensor.cuda()
    print(f"GPU: {gpu_tensor}")

cpu_tensor = rand_tensor.cpu()
print(f"CPU: {cpu_tensor}")

GPU: tensor([[0.7314, 0.9252, 0.3127],
        [0.4006, 0.4120, 0.0107]], device='cuda:0')
CPU: tensor([[0.7314, 0.9252, 0.3127],
        [0.4006, 0.4120, 0.0107]])


In [8]:
print(torch.__version__)

2.5.1


In [9]:
# Tensor运算

In [10]:
# 索引

tensor = torch.randn(4,4)
print(tensor)
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:,0]}")
print(f"最后一列: {tensor[:,-1]}")

tensor[:,1]=0
print(tensor)

tensor([[-1.3801,  0.6272, -1.9758, -1.8754],
        [-0.8079,  0.0892,  0.4582, -0.2175],
        [-0.2089, -0.2523,  0.3441,  0.2502],
        [-0.6154, -0.1220,  1.2747, -0.4221]])
第一行: tensor([-1.3801,  0.6272, -1.9758, -1.8754])
第一列: tensor([-1.3801, -0.8079, -0.2089, -0.6154])
最后一列: tensor([-1.8754, -0.2175,  0.2502, -0.4221])
tensor([[-1.3801,  0.0000, -1.9758, -1.8754],
        [-0.8079,  0.0000,  0.4582, -0.2175],
        [-0.2089,  0.0000,  0.3441,  0.2502],
        [-0.6154,  0.0000,  1.2747, -0.4221]])


In [11]:
# 算术运算

tensor = torch.tensor([[1,2],
                       [3,4]])
# 矩阵乘法
result = tensor @ tensor
print(result)

# 元素乘法
result_2 = tensor * tensor
print(result_2)

# 元素乘法
result_3 = tensor + tensor
print(result_3)

# 矩阵求和
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)

# 拼接

tensor_1 = torch.tensor([[1,2,3,4]])
tensor_2 = torch.tensor([[5,6,7,8]])

## 行方向拼接，行数增加
print(torch.cat([tensor_1,tensor_2], dim=0))
## 列方向拼接，列数增加
print(torch.cat([tensor_1,tensor_2], dim=1))

tensor([[ 7, 10],
        [15, 22]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[2, 4],
        [6, 8]])
tensor(10)
10
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [12]:
!pip install Pillow numpy

In [13]:
# Tensor数据转换

## NUMPY转TENSOR
import numpy as np

n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

## TENSOR转NUMPY
t = torch.ones(5)
n = t.numpy()
print(t)
print(n)

## 图片转TENSOR
from PIL import Image
import torchvision

image_path = r'cat.jpg'
image = Image.open(image_path)

transform = torchvision.transforms.ToTensor()
tensor_image = transform(image)

print(type(tensor_image))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>


In [14]:
## TENSOR转图片

import torch
from torchvision import transforms

tensor_image = torch.randn((3,244,244))
transformed_image = transforms.ToPILImage()(tensor_image)
save_path = r'form_tensor.jpg'
transformed_image.save(save_path)

In [22]:
## 综合案例-PyTorch处理图片
import torch
from torchvision import transforms
from PIL import Image

image_path = "cat.jpg"
save_path = "result.jpg"

### 加载图片
image = Image.open(image_path)

### 图片转换成TENSOR
transform = transforms.ToTensor()
tensor_image = transform(image)

print(tensor_image.shape)
print(tensor_image.device)

### 转入到显卡中
if torch.cuda.is_available():
    tensor_image = tensor_image.to("cuda")

print(tensor_image.device)

#### 修改每个像素值
tensor_image += 0.1

print(tensor_image)
### 转回到CPU中
tensor_image = tensor_image.cpu()
print(tensor_image.device)

### 保存
transformed_image = transforms.ToPILImage()(tensor_image)
transformed_image.save(save_path)


torch.Size([3, 560, 1440])
cpu
cuda:0
tensor([[[1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         ...,
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000]],

        [[1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         ...,
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000]],

        [[1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.1000, 1.1000,  ..., 1.1000, 1.1000, 1.1000],
         [1.1000, 1.